<meta charset="utf-8">
    
    <link rel="stylesheet" href="CSS/standard.css">
    <link href="https://fonts.googleapis.com/css?family=Oswald|Halant" rel="stylesheet"> <!--skrifttyper-->
        
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"> <!--Ikonsamling bruges i burgermenu-->
    <link rel="stylesheet" href="CSS/menustyle.css">
        